name: Node.js deploy to dist

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build-ext
      #checkout the dist branch
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: "to-be-published"
          ref: "dist"
      #copy the built dist content
      - name: Copy Dist To Be Published
        run: cp -rlf dist/* ./to-be-published/
      - name: Copy package.json
        run: cp -rlf package.json ./to-be-published
      #publish it
      - name: Publish content
        run: |
          cd ./to-be-published
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'ci: ${{github.event.head_commit.message}}'
          git push origin dist
