name: Node.js deploy to dist

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build-ext
      #checkout the dist branch
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          path: "to-be-published"
          ref: "dist"
      #copy the built dist content
      - name: Copy Dist To Be Published
        run: cp -rlf dist/* ./to-be-published/
      - name: Copy package.json
        run: cp -rlf package.json ./to-be-published
      #publish it
      - name: Publish content
        run: |
          cd ./to-be-published
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'ci: ${{github.event.head_commit.message}}'
          git push origin dist
