name: Node.js deploy to dist

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      #checkout the dist branch
      - uses: actions/checkout@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: "to-be-published"
          ref: "dist"
      #copy the built dist content
      - name: Copy Dist To Be Published
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cp -rlf dist/* ./to-be-published/
      - name: Copy package.json
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cp -rlf package.json ./to-be-published
      #publish it
      - name: Publish content
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd ./to-be-published
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'ci: ${{github.event.head_commit.message}}'
          git push origin dist
